customhost = "employee.clifhgpky1m3.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "cpac3009"
customdb = "employee"
custombucket = "chowkokkeong-employee"
customregion = "us-east-1"
